name: 'Trigger GitLab pipeline'
description: 'Trigger GitLab pipeline'
inputs:
  ci-api-v4-url:
    description: 'GitLab API v4 root URL'
    required: true
  project-id:
    description: 'GitLab project ID'
    required: true
  ref:
    description: 'GitLab project ref'
    required: true
  token:
    description: 'GitLab API access token'
    required: true
  schedule:
    description: 'Indication if it is a automatically scheduled request'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'index.js'
